name: Electric

on:
  push:
    branches: [main]
    paths:
      - electric/**
      - .github/workflows/electric.yml

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only
        working-directory: electric
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
